#!/usr/bin/env python3
"""Keep the exterior ground variant on the project's complete PS1/URP passes.

Ps1Lit remains untouched. Only the forward surface hook and two interpolators
are added; lighting keywords, PS1 snap, shadows and depth passes stay upstream.
Run --check after a URP or Ps1Lit upgrade. No Unity/package cache is modified.
"""
from pathlib import Path
import argparse
import uuid

ROOT = Path(__file__).resolve().parents[1]
SHADERS = ROOT / "Assets/Resources/Shaders"


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise ValueError("Upstream shader contract changed: " + old[:90])
    return text.replace(old, new, 1)


def outputs():
    shader = (SHADERS / "Ps1Lit.shader").read_text(encoding="utf-8")
    shader = shader[shader.index('Shader "'):]
    shader = replace_once(shader, 'Shader "Bar Promenade/PS1 Lit"',
                          'Shader "Bar Promenade/Layered Ground"')
    shader = replace_once(shader, '    Properties\n    {', '''    Properties
    {
        _GroundResponse("Linear material response", 2D) = "white" {}
        _GroundSubstrateMap("Snow substrate", 2D) = "white" {}
        _GroundSubstrateResponse("Snow substrate response", 2D) = "white" {}
        _GroundAsphaltMap("Snow asphalt substrate", 2D) = "white" {}
        _GroundAsphaltResponse("Snow asphalt response", 2D) = "white" {}
        _GroundAsphaltColor("Snow asphalt tint", Color) = (1,1,1,1)
        _GroundJunctionAtlas("Snow junction substrate", 2D) = "white" {}
        _GroundJunctionResponse("Snow junction response", 2D) = "white" {}
        _GroundJunctions("Painted snow junctions", Float) = 0
        _GroundSubstrateColor("Snow substrate tint", Color) = (1,1,1,1)
        _GroundKind("Surface family", Float) = 0
        _GroundWetness("Local weather amount", Range(0,1)) = 0
        _GroundCityClimate("City ground weather", Float) = 0
        _GroundRoadCoordinates("Authored road coordinates", Float) = 0
        _GroundVertexData("Existing snow state", Float) = 0''')
    shader = shader.replace('#pragma target 2.0', '#pragma target 3.5', 1)
    shader = replace_once(shader,
        '#include "Packages/com.unity.render-pipelines.universal/Shaders/LitForwardPass.hlsl"',
        '#include "GroundSurfaceForwardPass.hlsl"')
    packages = list((ROOT / "Library/PackageCache").glob(
        "com.unity.render-pipelines.universal@*/Shaders/LitForwardPass.hlsl"))
    if len(packages) != 1:
        raise ValueError("Expected one imported URP LitForwardPass source")
    forward = packages[0].read_text(encoding="utf-8")
    forward = forward.replace('"LitInput.hlsl"',
        '"Packages/com.unity.render-pipelines.universal/Shaders/LitInput.hlsl"')
    forward = replace_once(forward, 'struct Attributes\n{', '''#include "GroundSurfaceLayers.hlsl"

struct Attributes
{
    float4 groundRoad : TEXCOORD3;
    half4 groundState : COLOR;''')
    forward = replace_once(forward, 'struct Varyings\n{', '''struct Varyings
{
    float4 groundRoad : TEXCOORD11;
    half4 groundState : TEXCOORD12;''')
    forward = replace_once(forward, '    output.uv = TRANSFORM_TEX(input.texcoord, _BaseMap);',
        '''    output.groundRoad = input.groundRoad;
    output.groundState = input.groundState;
    output.uv = TRANSFORM_TEX(input.texcoord, _BaseMap);''')
    forward = replace_once(forward, '    InitializeStandardLitSurfaceData(input.uv, surfaceData);',
        '''    InitializeStandardLitSurfaceData(input.uv, surfaceData);
    half groundRelief;
    ApplyGroundLayers(input.uv, input.positionWS, input.normalWS,
        input.groundRoad, input.groundState, surfaceData, groundRelief);''')
    forward = replace_once(forward, '    InitializeInputData(input, surfaceData.normalTS, inputData);',
        '''    InitializeInputData(input, surfaceData.normalTS, inputData);
    inputData.normalWS = GroundReliefNormal(input.positionWS, inputData.normalWS, groundRelief);''')
    header = '// Generated by tools/build-ground-surface-shader.py; edit its hooks or GroundSurfaceLayers.hlsl.\n'
    return {path: '\n'.join(line.rstrip() for line in value.splitlines()) + '\n'
            for path, value in {
                SHADERS / 'GroundSurfaceLit.shader': header + shader,
                SHADERS / 'GroundSurfaceForwardPass.hlsl': header + forward}.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, value in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != value:
                raise ValueError('Regenerate ground shader: ' + str(path))
        else:
            path.write_text(value, encoding='utf-8', newline='\n')
        meta = Path(str(path) + '.meta')
        if not args.check and not meta.exists():
            importer = 'ShaderImporter' if path.suffix == '.shader' else 'ShaderIncludeImporter'
            guid = uuid.uuid5(uuid.NAMESPACE_URL, path.relative_to(ROOT).as_posix()).hex
            meta.write_text(f'fileFormatVersion: 2\nguid: {guid}\n{importer}:\n  externalObjects: {{}}\n  userData:\n  assetBundleName:\n  assetBundleVariant:\n', encoding='utf-8')
    print('Ground shader source hooks match the complete upstream passes.')


if __name__ == '__main__':
    main()
